apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-k8s-frontend-deployment
spec:
  selector:
    matchLabels:
      app: yolo-k8s-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: yolo-k8s-frontend
    spec:
      containers:
        - name: yolo-k8s-frontend
          image: ekibet/yolo-k8s-frontend:1.0.2
          tty: true
          ports:
            - containerPort: 3000