apiVersion: v1
kind: Service
metadata:
  name: yolo-k8s-frontend-service
spec:
  selector:
    app: yolo-k8s-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer