apiVersion: v1
kind: Service
metadata:
  name: yolo-k8s-backend-service
spec:
  selector:
    app: yolo-k8s-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer