apiVersion: v1
kind: Service
metadata:
  name: yolo-k8s-database-service
spec:
  selector:
    app: yolo-k8s-database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: LoadBalancer